#!/usr/bin/env bash
# E2E script to setup environment-specific secrets
# Reads context from $ZTC_CONTEXT_FILE and secrets from environment variables
#
# This script orchestrates:
# 1. Generate Age keypair (or retrieve from S3)
# 2. Backup Age key to S3
# 3. Convert ~/.ztc/secrets to .env format
# 4. Generate encrypted secrets
# 5. Export keys for subsequent use

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HELPERS_DIR="$SCRIPT_DIR/../shared"
GENERATORS_DIR="$SCRIPT_DIR/../generators"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   E2E Environment Secrets Setup                              ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Validate context file
if [[ -z "${ZTC_CONTEXT_FILE:-}" ]]; then
    echo "ERROR: ZTC_CONTEXT_FILE not set" >&2
    exit 1
fi

if [[ ! -f "$ZTC_CONTEXT_FILE" ]]; then
    echo "ERROR: Context file not found: $ZTC_CONTEXT_FILE" >&2
    exit 1
fi

echo -e "${GREEN}✓ Context file validated${NC}"
echo ""

# Step 1: Generate Age keypair
echo -e "${BLUE}[1/5] Generating Age keypair...${NC}"
source "$SCRIPT_DIR/08b-generate-age-keys.sh"

if [ -z "${AGE_PRIVATE_KEY:-}" ]; then
    echo -e "${RED}✗ Failed to generate/retrieve Age key${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Age keypair ready${NC}"
echo ""

# Step 2: Backup to S3
echo -e "${BLUE}[2/5] Backing up Age key to S3...${NC}"
"$SCRIPT_DIR/08b-backup-age-to-s3.sh"

echo -e "${GREEN}✓ Age key backed up to S3${NC}"
echo ""

# Step 3: Convert ~/.ztc/secrets to .env format
echo -e "${BLUE}[3/5] Converting secrets to .env format...${NC}"
ENV_FILE="/tmp/ztc-secrets-$$.env"
if ! "$HELPERS_DIR/secrets-to-env.sh" > "$ENV_FILE"; then
    echo -e "${RED}✗ Failed to convert secrets${NC}"
    exit 1
fi

echo -e "${GREEN}✓ .env file created: $ENV_FILE${NC}"
echo ""

# Step 4: Generate encrypted secrets
echo -e "${BLUE}[4/5] Generating encrypted secrets...${NC}"

# Create secrets directory
SECRETS_DIR="platform/generated/argocd/overlays/main/core/secrets"
mkdir -p "$SECRETS_DIR"

SHARED_DIR="$SCRIPT_DIR/../shared"

# Generate .sops.yaml config file in platform directory
if [ -z "${AGE_PUBLIC_KEY:-}" ]; then
    echo -e "${RED}✗ AGE_PUBLIC_KEY not set${NC}"
    exit 1
fi

mkdir -p platform
python3 "$SHARED_DIR/generate_sops_config.py" "$AGE_PUBLIC_KEY" "platform/.sops.yaml"

# Run Python generator scripts (no longer need templates_dir argument)
CORE_FILES=$(python3 "$GENERATORS_DIR/generate_core_secrets.py" "$SECRETS_DIR")
TENANT_FILES=$(python3 "$GENERATORS_DIR/generate_tenant_registry_secrets.py" "$SECRETS_DIR")

# Encrypt generated files with SOPS
SOPS_CONFIG="platform/.sops.yaml"
for file in $(echo "$CORE_FILES" | jq -r '.[]'); do
    if sops --config "$SOPS_CONFIG" -e -i "$SECRETS_DIR/$file" 2>/dev/null; then
        echo -e "${GREEN}  ✓ $file${NC}"
    else
        echo -e "${RED}  ✗ Failed to encrypt: $file${NC}"
        rm -f "$SECRETS_DIR/$file"
    fi
done

for file in $(echo "$TENANT_FILES" | jq -r '.[]'); do
    if sops --config "$SOPS_CONFIG" -e -i "$SECRETS_DIR/$file" 2>/dev/null; then
        echo -e "${GREEN}  ✓ $file${NC}"
    else
        echo -e "${RED}  ✗ Failed to encrypt: $file${NC}"
        rm -f "$SECRETS_DIR/$file"
    fi
done

# Create KSOPS generator and kustomization
ALL_FILES=$(echo "$CORE_FILES $TENANT_FILES" | jq -s 'add')

if [ "$(echo "$ALL_FILES" | jq 'length')" -gt 0 ]; then
    cat > "$SECRETS_DIR/ksops-generator.yaml" << EOF
# Generated by KSOPS adapter
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: core-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
EOF
    
    for file in $(echo "$ALL_FILES" | jq -r '.[]'); do
        echo "  - ./$file" >> "$SECRETS_DIR/ksops-generator.yaml"
    done
    
    cat > "$SECRETS_DIR/kustomization.yaml" << EOF
# Generated by KSOPS adapter
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- ksops-generator.yaml
EOF
    echo -e "${GREEN}  ✓ kustomization.yaml${NC}"
fi

# Cleanup
rm -f "$ENV_FILE"

echo -e "${GREEN}✓ Encrypted secrets generated${NC}"
echo ""

# Step 5: Summary
echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Setup Complete                                             ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}✅ Environment secrets setup complete${NC}"
echo -e "${GREEN}✓ Age keypair generated/retrieved${NC}"
echo -e "${GREEN}✓ Age key backed up to S3${NC}"
echo -e "${GREEN}✓ Secrets encrypted and stored in: $SECRETS_DIR${NC}"
echo ""
